stages:
  - linting
  - build
  - deploy
  - clearing

linting:
  stage: linting
  image: python:3.10-slim

  before_script:
    - python3 --version
    - pip --version
    - pip install isort black

  script:
    - sleep 10
    - isort . -l 120 --profile black --check-only
    - black -l 120 --check .
  when: always

build and publish:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo $CI_REGISTRY
    - echo $CI_REGISTRY_SA_KEY
    - echo $CI_PROJECT_DIR
    - echo $CI_PROJECT_PATH
    - echo $CI_COMMIT_SHORT_SHA
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n "json_key:${CI_REGISTRY_SA_KEY}" | base64 | tr -d '\n' )\"}}}" > /kaniko/.docker/config.json
    - cat /kaniko/.docker/config.json
    - env
    - >-
      /kaniko/executor
      --context "$CI_PROJECT_DIR"
      --dockerfile "$CI_PROJECT_DIR/dockerfile"
      --destination "$CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_SHORT_SHA"
  when: manual

.install_yc: &install_yc
  - apt update
  - apt install -y curl jq
  - curl -f -s -LO https://storage.yandexcloud.net/yandexcloud-yc/install.sh
  - bash install.sh -i /usr/local/yandex-cloud -n
  - ln -s /usr/local/yandex-cloud/bin/yc /usr/local/bin/yc
  - yc --version
  - yc config set format json
  - yc config set folder-id $CI_FOLDER_ID
  - echo $CI_SERVERLESS_SA_KEY > serverless-sa-key.json
  - yc config set service-account-key serverless-sa-key.json

create container:
  stage: deploy
  image: ubuntu:20.04
  script:
    - *install_yc
    - env
    - yc serverless container list
    - >-
      export CONTAINER_ID=$(yc serverless container list | 
      jq --arg CI_PROJECT_NAME "$CI_PROJECT_NAME" '.[] | select(.name==$CI_PROJECT_NAME) | .id')
    - |-
      if [[ $CONTAINER_ID == "" ]]; then
        echo "CREATING NEW CONTAINER"
        export CONTAINER_ID=$(yc serverless container create --name $CI_PROJECT_NAME | jq '.id')
      else
        echo "CONTAINER $CI_PROJECT_NAME ALREADY EXISTS"
      fi
    - yc serverless container allow-unauthenticated-invoke --name $CI_PROJECT_NAME
    - echo "CONTAINER ID IS $CONTAINER_ID"
  when: on_success
  needs:
    - build and publish

create revision:
  stage: deploy
  image: ubuntu:20.04
  script:
    - *install_yc
    - yc serverless container list
    - >-
      export CONTAINER_ID=$(yc serverless container list | 
      jq --arg CI_PROJECT_NAME "$CI_PROJECT_NAME" '.[] | select(.name==$CI_PROJECT_NAME) | .id')
    - |-
      if [[ $CONTAINER_ID == "" ]]; then
        echo "CAN NOT FIND $CI_PROJECT_NAME CONTAINER"
        exit 1
      else
        echo "CONTAINER $CI_PROJECT_NAME EXISTS"
      fi
    - >-
      yc serverless container revision deploy
      --container-name $CI_PROJECT_NAME
      --image $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_SHORT_SHA
      --cores 1
      --core-fraction 5
      --memory 128MB
      --service-account-id `echo $CI_SERVERLESS_SA_KEY | jq -r '.service_account_id'`
  when: on_success
  needs:
    - build and publish

delete container:
  stage: clearing
  image: ubuntu:20.04
  script:
    - *install_yc
    - yc serverless container list
    - >-
      export CONTAINER_ID=$(yc serverless container list | 
      jq --arg CI_PROJECT_NAME "$CI_PROJECT_NAME" '.[] | select(.name==$CI_PROJECT_NAME) | .id')
    - |-
      if [[ $CONTAINER_ID == "" ]]; then
        echo "CAN NOT FIND $CI_PROJECT_NAME CONTAINER"
        exit 0
      else
        echo "CONTAINER $CI_PROJECT_NAME EXISTS"
      fi
    - yc serverless container delete --name solver
  when: manual

delete image:
  stage: clearing
  image: ubuntu:20.04
  script:
    - *install_yc
    - echo $CI_REGISTRY_SA_KEY > registry-sa-key.json
    - yc config set service-account-key registry-sa-key.json
    - export REPOSITORY_NAME=`echo $CI_REGISTRY/$CI_PROJECT_PATH | sed s/"cr.yandex\/"//`
    - >-
      export IMAGE_ID=$(yc container image list --repository-name $REPOSITORY_NAME
      | jq '.[] | select(.tags[]=="$CI_COMMIT_SHORT_SHA") | .id')
    - |-
      if [[ $IMAGE_ID == "" ]]; then
        echo "CAN NOT FIND $REPOSITORY_NAME:$CI_COMMIT_SHORT_SHA IMAGE"
        exit 1
      else
        echo "CONTAINER $CI_PROJECT_NAME EXISTS"
      fi
  when: manual
  needs:
    - delete container
